### ISSUE TITLE
Curate initial dataset for ML team

### ISSUE THREAD

**Issue by dlebauer** [genophenoenvo/terraref-datasets#1]
These are the data that we want to start with:

![image](https://user-images.githubusercontent.com/464871/63547603-58528700-c4e1-11e9-9bb7-76e0258c43bf.png)

As an idea, there are some examples curated for another project here: https://terraref.ncsa.illinois.edu/d3m/ but ... the shape of the data will be different, and we also need to work on how to properly curate / annotate these (#2).

### Genomics data

Need to get feedback from Pankaj on what genomics data to include; hopefully can use data from http://datacommons.cyverse.org/browse/iplant/home/shared/terraref

### Phenotypes

* Start with Seasons 4 and 6
* Instead of emergence / flowering dates, need planting date and days to emergence / flowering (will need to keep track of this / discuss what makes sense; feeback from Pankaj, Arun, Remco etc)
* see https://traitvis.workbench.terraref.org/ for view of what data is available

### Environment

* from geostreams + managements table 
* Just need data during the seasons
* also add growing degree days

**Comment by dlebauer** [comment]
We will use these from the BAP population: http://datacommons.cyverse.org/browse/iplant/home/shared/terraref/genomics/derived_data/bap/resequencing/danforth_center/version1/gvcf

There is one file per genotype

This is the combined file: http://datacommons.cyverse.org/browse/iplant/home/shared/terraref/genomics/derived_data/bap/resequencing/danforth_center/version1/hapmap

**Comment by diatomsRcool** [comment]
Here's an example of what I'm imagining the data will look

| Plot | Soil Moisture Day 1 Max | Soil Moisture Day 1 Min | Soil Moisture Day 1 Mean | etc for all params and all days | Emergence Date | all phenotypes | growing degree days at emergence | Anything else you think is interesting |
| --------- | ----------- | ---------- | ---------- | ---------- | ----------- | --------- | ---------- | ------------ |
| Plot 1 | 4.2 | 2.3 | 3.2 | etc | 20 | etc | 10 | etc |

I'm thinking we should be using dates that just count from time zero at planting and not actual calendar dates.

**Comment by dlebauer** [comment]
@diatomsRcool so to confirm, you are looking for a table with one row per plot? I expect these will end up 100s of columns wide if we have min/mean/max for each environmental parameter x day.

Other than soil moisture, each column of environmental data will have the same value repeated.

**Comment by diatomsRcool** [comment]
Yes. @remcochang and @rossarun can override me.

**Comment by MagicMilly** [comment]
@diatomsRcool @remcochang @rossarun 

**Works in Progress**:

* [Google Sheet](https://docs.google.com/spreadsheets/d/1o13Gy0p6-1ncgWwZ_QNM4yJxugf533o3DL-7zk4sn9g/edit?usp=sharing) where you can view, comment, and download.
* [Gists](https://gist.github.com/MagicMilly) where you can view, comment, and download data in `.csv` format within a `.zip` file. 
* Python code within Jupyter [notebooks](https://github.com/genophenoenvo/terraref-datasets/tree/gh5-phenotypes/notebooks) used for data transformations.

You can comment on the spreadsheets and gists directly, but it would be best to post questions and comments here so that we can all see them. Thank you!

**Comment by dlebauer** [comment]
* in tall [format traits](https://docs.google.com/spreadsheets/d/1o13Gy0p6-1ncgWwZ_QNM4yJxugf533o3DL-7zk4sn9g/edit#gid=148032206) 
   * for biomass, we only want the dry biomass (not wet and not moisture content)
   * remove weather data
* add new sheets w/ 
   * time series of canopy height
   * height just before harvest
* gap fill weather w/ backup weather station data
* for precip rate - 
    * just include total and max rate
    * add cumulative precip

**Comment by MagicMilly** [comment]
First iteration of ML training data can be found in the [Google Drive](https://drive.google.com/drive/folders/1B9Hmj2Xwu0J9arTfhFiFZqkEktSeag63?usp=sharing) for now. Closing this issue and creating new ticket(s) for second iteration and including genomics data.
