### ISSUE TITLE
Reformat weather data for all seasons

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#101]
Incorporate Ryan's feedback from [Issue 36](https://github.com/genophenoenvo/docker/issues/36) in docker [repo](https://github.com/genophenoenvo/docker) to ensure continuity for all seasons where possible:

**MAC Season 4**
- [x] Change column names to include units (vpd in KPa)
- [x] Copy to new weather folder on GDrive
- [x] Upload to CyVerse
- [x] Replace any existing versions in other folders on GDrive
~Replace any existing versions in other folders on CyVerse~ 

**MAC Season 6**
- [x] Change column names to include units (vpd in KPa)
- [x] Add cumulative precipitation
- [x] Upload to weather folder on GDrive
- [x] Upload to CyVerse

**KSU**
- [x] Add Day of Year
- [x] Calculate and add vapor pressure deficit, using hourly values to obtain the average daily values
- [x] Upload to weather folder on GDrive
- [x] Upload to CyVerse

**Clemson**
- [x] Slice for season dates only
- [x] Add growing degree days
- [x] Upload to weather folder on GDrive
- [x] Upload to CyVerse

**README**

- [x] describe each file and contents
- [x] define / cite source of each weather dataset

**Comment by MagicMilly** [comment]
CyVerse download links for updated weather data

- MAC Season 4: https://de.cyverse.org/dl/d/E11D3666-CD04-426F-B833-85DB6B39C574/mac_season_4_weather.csv

- MAC Season 6: https://de.cyverse.org/dl/d/33B533EC-9EB0-4BB4-AAA2-650FAD4BD1D5/mac_season_6_weather.csv

- KSU: https://de.cyverse.org/dl/d/F9FE37D0-BF57-4238-9F61-71C1D34B0B18/ksu_weather.csv

- Clemson: https://de.cyverse.org/dl/d/08675B05-F02E-4AB1-A934-8EFAD8DD3296/clemson_weather.csv

The file path on CyVerse is `/iplant/home/shared/genophenoenvo/data/weather_data`
Updated weather cleaning [notebooks](https://github.com/MagicMilly/for-data-publication/tree/main/notebooks)
Previous weather data versions on GDrive were replaced in addition to being added in a new `weather_data` [folder](https://drive.google.com/drive/folders/1ILwvP2mZdUHJ4SnJy4bo_XrBAJ54mOlp?usp=sharing)

**Comment by rbartelme** [comment]
Please update the column named `vpd_kpa` to `vpd_mean_kpa` in the KSU and Clemson data.

**Comment by dlebauer** [comment]
* In general I would remove units from the variable names but define variables and units in the README
* Make sure that variable naming is consistent across datasets
* Also there are a lot of extra variables that are inconsistent across datasets. I would start with the common variables and we can figure out if we need to add more later.

**Comment by MagicMilly** [comment]
**Column names in this order for all four weather datasets**
- `date`
- `day_of_year`
- `temp_min`
- `temp_max`
- `temp_mean`
- `gdd`
- `rh_min`
- `rh_max`
- `rh_mean`
- `vpd_mean`
- `precip`
- `precip_cumulative`
- `first_water_deficit_treatment`
- `second_water_deficit_treatment`

**Defined in README**
- units
- any calculations
- all weather stations with their location, elevation, lat, and lon
- season dates
- links to CyVerse downloads of raw data (which were used in the notebook vs. local file)
- links to raw data sources 
- uploaded to CyVerse https://de.cyverse.org/dl/d/0AD5C871-63F0-4DAD-9EE0-743B20BBEF23/README.md

**Updated CyVerse download URLs**
- MAC season 4 https://de.cyverse.org/dl/d/6D959379-0442-41FE-8BEE-890866ACF037/mac_season_4_weather.csv
- MAC season 6 https://de.cyverse.org/dl/d/C6219045-8114-4068-B924-8C2CD54AB9FD/mac_season_6_weather.csv
- KSU https://de.cyverse.org/dl/d/F53F6574-CE80-408E-B8C8-8983CB287F96/ksu_weather.csv
- Clemson https://de.cyverse.org/dl/d/1EB28C81-10A1-4E1B-A406-1D0C6A20AF2D/clemson_weather.csv

**One weather data cleaning notebook to ~rule them all~ replace the other four**
- `weather_data_cleaning.ipynb` https://de.cyverse.org/dl/d/2270993B-3F55-4B52-986D-5D7B876C2ED3/weather_data_cleaning.ipynb
- I'm unable to delete older notebooks if I did not upload them myself, which I'm hoping @tyson-swetnam and I will be able to do together
- Also on [GitHub](https://github.com/MagicMilly/for-data-publication/tree/main/notebooks)

**Updated weather data folder also on [GDrive](https://drive.google.com/drive/folders/1N27fFxqHg3b36SrQ5X4lbcPFv1OUgxu7?usp=sharing)**

Please comment on this ticket with any questions or feedback
