### ISSUE TITLE
Complete PR by adding description of linked ontology

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#103]
- As a follow-up to issue #97, complete pull request by adding a description of the linked ontology csv and json file to the repo's README
- Create issue for David to review PR once ready

**Comment by MagicMilly** [comment]
Modified `README.md` as requested in [PR](https://github.com/terraref/brapi/pull/45) for adding ontology data to `terraref/brapi` repository

**Comment by Chris-Schnaufer** [comment]
@MagicMilly Can this be closed?

**Comment by MagicMilly** [comment]
@Chris-Schnaufer Yes, thank you for that reminder... for a ticket from Sprint 44.
