### ISSUE TITLE
Sorghum bicolor modeling: height vs. gdd

### ISSUE THREAD

**Issue by rbartelme** [genophenoenvo/terraref-datasets#107]
Rewritten objectives:

- [x] intermediate season 6 wide format output
- [x] subset season 6 with 10 random cultivars with plot, cultivar, canopy_height, and gdd
- [x] develop `brm` model of logistic growth with stan model output using subset data

**Comment by rbartelme** [comment]
Found the above for a single cultivar using @KristinaRiemer's [example](https://terraref.github.io/tutorials/combining-trait-weather-and-image-datasets.html#plot-and-model-relationship-between-gdd-and-canopy-cover-for-each-cultivar). However, I had issues with outliers in the cultivar example, since the max `c` in the tutorial was quite different than the data from the database. Two dates had canopy heights above the final max. Maybe this was panicle height? And it's mislabeled in the db?

**Comment by rbartelme** [comment]
Underestimated difficulty of task, moving to next sprint and adjusting points accordingly.

**Comment by dlebauer** [comment]
Note that the tutorials were written with the intention of using the simplest model that could illustrate this approach. This fits a growth curve for each cultivar independently, but it would be good to fit all cultivars at the same time. This would help reduce the influence of outliers. 

Here is an example with nlme: https://stackoverflow.com/a/55779001  and for a Bayesian approach (which might be over complicated but could allow more flexibility when dealing with missing data) check out other examples with the brms interface to Stan, such as this https://bookdown.org/ajkurz/Statistical_Rethinking_recoded/monsters-and-mixtures.html.

**Comment by rbartelme** [comment]
Model successfully ran on a subset of the data, with the markov chains converging. Follow up issues for next sprint will be created to derive values for the logistic growth equation.
