### ISSUE TITLE
Add script for cleaning soil data

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#110]
Follow-up ticket to #99 and WIP [PR](https://github.com/genophenoenvo/soil-data/pull/2). May integrate with Google Drive or put in private directory on CyVerse. Will need to work on writing scripts with Kristina and Julian before I can complete this ticket.

**Comment by dlebauer** [comment]
If the notebook works this is low priority

**Comment by MagicMilly** [comment]
David can grant access to this private repo if needed
