### ISSUE TITLE
Prepare demo for TRIPODS-HDR workshop

### ISSUE THREAD

**Issue by KristinaRiemer** [genophenoenvo/terraref-datasets#115]

**Comment by MagicMilly** [comment]
May no longer be doing demo due to new proposed [agenda](https://genophenoenvo.github.io/workshop/agenda.html)?

**Comment by KristinaRiemer** [comment]
I assume not?

**Comment by MagicMilly** [comment]
Removing milestone, point estimate, and closing ticket due to change in workshop plans
