### ISSUE TITLE
Modify NEON table with column names and download from R package

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#117]
Per David's feedback on #95 for the NEON data table cleaning script

- [ ] change column names in the NEON cleaning script to match TERRA-REF column names
    - [ ] `sitename` column can include all location information
    - [ ] keep `uid` column but drop all (non-location) columns that would not be found in TERRA-REF processed data
- [ ] Download data using `neonstore` R package
    - [ ] Make changes to how the script pulls data, using the R package

**Comment by KristinaRiemer** [comment]
I thiiiiink I've addressed all of @dlebauer's comments in [a pull request](https://github.com/genophenoenvo/neon-datasets/pull/1) in [the new NEON data repo](https://github.com/genophenoenvo/neon-datasets). 

@MagicMilly we should add your Python script for doing the initial steps of this work to the `plant_cover`folder in that repo too.

**Comment by MagicMilly** [comment]
@KristinaRiemer I don't have a script to add to that repo because I never created (or modified) one based on David's feedback.

**Comment by KristinaRiemer** [comment]
@MagicMilly I was thinking of [this work](https://github.com/MagicMilly/neon-data/blob/main/code/neon_table_prototype.py) that you did, but it doesn't have to be added.
