### ISSUE TITLE
Meet with Ramona and Jeannette to develop a plan for curating and publishing data

### ISSUE THREAD

**Issue by dlebauer** [genophenoenvo/terraref-datasets#2]
* For sample datasets, what metadata to put in README
* Where to publish and get a doi
* Take notes and propose a path forward

**Comment by Chris-Schnaufer** [comment]
When a dataset gets created, how do we get a DOI?

**Comment by MagicMilly** [comment]
Meeting with Jeanette on Thursday 11/14 at 10 AM

**Comment by MagicMilly** [comment]
Ramona will be hosting a CyVerse Webinar on 11/22 **Don't Let Your Data Drag You Down**

> Datasets are becoming larger and more complicated, with many people often contributing to and using the same data. Simultaneously, funders, publishers, and research institutions are beginning to require open data. These pressures can leave researchers and project managers stressed out and struggling to manage their data.

> No worries, CyVerse has got your back! CyVerse's data management expert Ramona Walls will take you through key features of the CyVerse platform that support managing your data throughout the entire data life cycle – all in one place! From easy bulk uploads, to permissions management, to using metadata, to getting Digital Object Identifiers (DOI), this webinar provides the best practices and helpful hints that any scientist needs to keep the data deluge at bay.

Will schedule meeting with Ramona after the webinar to have better / more specific questions.

**Comment by MagicMilly** [comment]
Created [pull request](https://github.com/az-digitalag/organization/pull/127#issue-341935977) on DIAG Meetings repo for Jeanette to review.
