### ISSUE TITLE
Determine how to convert ontology annotations to a dictionary

### ISSUE THREAD

**Issue by dlebauer** [genophenoenvo/terraref-datasets#21]
following https://github.com/genophenoenvo/terraref-datasets/issues/9 where variables were annotated w/ ontology terms in [this spreadsheet](https://docs.google.com/spreadsheets/d/1o13Gy0p6-1ncgWwZ_QNM4yJxugf533o3DL-7zk4sn9g/edit?usp=sharing)

Next step is to generate a dictionary 

* what uris should we use?
* any specific data structure (json-ld? BrAPI?)
* how do we interpret / label the comments about exact, subclass, related, and other ontology terms?

**Comment by diatomsRcool** [comment]
The first two points may require discussion, but on the last point, I would apply OWL or SKOS terms. That's what Laurel was referring to. They will match up exactly.

**Comment by dlebauer** [comment]
Can we use the BrAPI 2.0 specification https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI-Phenotyping/2.0#/Methods/post_methods

It has a field to link to ontologies / terms 

![8A45B47A-1796-4361-952A-50DF665917E4](https://user-images.githubusercontent.com/464871/72224152-d0baf280-352b-11ea-8a79-d0d84a3f9920.jpeg)

**Comment by diatomsRcool** [comment]
I am not familiar with BrAPI, but I don't see a place for the actual ontology term ID. Looks like they are just referencing the whole ontology. I'm not 100% sure why you need a dictionary, but you could use the  variable as the key and the value could be pipe-delimited CURIE and comment. Like 'FlowerColor':'TO007890|exact'. Although I'm just realizing that the CURIE will have a colon in it and thus be a pain to use in a dictionary. Maybe 'FlowerColor':'TO|007890|exact'. Does that help?

**Comment by Chris-Schnaufer** [comment]
@MagicMilly What's the status on this?

**Comment by MagicMilly** [comment]
I've added the termId column to the spreadsheet as discussed with Ramona but still need to follow up on 

- [ ] methods
- [ ] availability of terms for subclasses of traits (i.e. end of season height as a subclass of plant height)
- [x] once complete, export spreadsheet as `.csv` > dict > `.json`

![Screen Shot 2020-03-26 at 7.41.23 AM.png](https://images.zenhubusercontent.com/5dae068e86447a00015c37c5/d544e5a7-5018-4505-a637-16648a835217)

**Comment by MagicMilly** [comment]
Follow-up tickets:
- #45 
- #46
