### ISSUE TITLE
Determine if more precise weather data can be obtained

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#23]
- [ ] Determine if more precise coordinates for Geostreams data is available
- [ ] Obtain more specific feedback about which weather data the researchers would like to use:
        - hourly
        - daily
        - weather station
        - gantry
        - all of the above
- [ ] If using Geostreams data, fill missing values with data from weather station

Daily weather station data is currently available in the [Google Drive](https://drive.google.com/drive/folders/1B9Hmj2Xwu0J9arTfhFiFZqkEktSeag63?usp=sharing)

**Comment by dlebauer** [comment]
We don't have more precise data technically we could get it for a subset of the sensors but we assume that the weather data applies to the entire field so this would require a bit of thought, starting with if it would even be meaningful. 

Soil data is variable, but not met (for the terraref data).
