### ISSUE TITLE
Questions about ontology annotation

### ISSUE THREAD

**Issue by dlebauer** [genophenoenvo/terraref-datasets#36]
Following up on https://github.com/genophenoenvo/terraref-datasets/issues/20 and #21 ... the variables have been assigned ontology terms in https://docs.google.com/spreadsheets/d/1o13Gy0p6-1ncgWwZ_QNM4yJxugf533o3DL-7zk4sn9g/edit#gid=0 but there are . a few things I'd like to clarify:

* should we be using the Trait Ontology or the Sorghum ontology or ???
* How should we differentiate between two methods used to measure the same property (e.g. plant height with ruler vs laser scanner)?
* what is the appropriate url to reference for these terms? 
* Other questions added as comments in the spreadsheet.

**Comment by jaiswalp** [comment]
should we be using the Trait Ontology or the Sorghum ontology or ???
> For now use the TO. Sorghum CO needs some work
How should we differentiate between two methods used to measure the same property (e.g. plant height with ruler vs laser scanner)?
> Yes, the Sorghum CO will likely create two different methods/variables based on this argument. TO stays generic from the Trait observation perspective. One TO term may map one Sorghum CO which maps to one to many variables.
what is the appropriate url to reference for these terms?
> For TO: Days to germinate (TO:0006061)  http://browser.planteome.org/amigo/term/TO:0006061
> CO: sorghum plant number - counting method (CO_324:0000486) : URL is same as above, just replace the term_ID e.g. http://browser.planteome.org/amigo/term/CO_324:0000486

**Comment by MagicMilly** [comment]
I've converted the spreadsheet to a `.json` file, now containing permanent urls for trait ontology terms (`termId`) and crop ontology terms (`coPermalink`), where available. The file can be found in my forked repo [here](https://github.com/MagicMilly/terraref-datasets/blob/master/data/trait_ontologies.json).

@jaiswalp and @diatomsRcool Is this an appropriate format for getting started? Any feedback is appreciated.

**Comment by dlebauer** [comment]
@MagicMilly what is the status of this issue?

**Comment by diatomsRcool** [comment]
I think its a good way to get started for the moment. As we move into more uncontrolled environments with more species we may have to do something else.

**Comment by MagicMilly** [comment]
Will have contrib/ PRs for ontologies.json, methods.json, and traits.json by the end of this Sprint as described in issue #77. Next steps will be to add to BrAPI as described in new ticket #92 and will close this issue.
