### ISSUE TITLE
Generate structured metadata using RMarkdown and EML and/or dataspice package

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#37]
Rather than the readme-style metadata, generate structured metadata by pulling directly from betydb where possible using RMarkdown and the EML and/or dataspice package.

Review work by david so far in the dryad branch of terraref/data-paper - see PR in https://github.com/terraref/data-paper/pulls, particularly the Dryad-README.Rmd and methods.Rmd.

**Comment by dlebauer** [comment]
You can start by reviewing this PR to see how I have begun to generate EML metadata in the Dryad-README.Rmd and methods.Rmd files https://github.com/terraref/data-paper/pulls

**Comment by MagicMilly** [comment]
Have generated metadata for one small dataset (aboveground dry biomass) with `EML` and `emldown` and will apply to the other datasets for Issues #33 and #38
