### ISSUE TITLE
Continue working on action items for UA Data Repo early adopters

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#48]
Have uploaded a small dataset to practice going through the process without publishing and will probably work through some of it with David and / or keep list of questions as they come up (i.e. which keywords do we want to associate with our derived data?).

**Comment by MagicMilly** [comment]
This will be complete (with details of what I've done) by end of this Sprint

**Comment by MagicMilly** [comment]
Added and saved to Data Repo:

- description draft (includes limited metadata)
- some author info
- license
- keywords
- categories
- title draft

Still needed:

- author info and order
- References (i.e. David's data paper)
- README.txt metadata from template _or_ more detailed generated XML metadata
- add other files as needed

**Comment by Chris-Schnaufer** [comment]
Tickers were written for still needed items
