### ISSUE TITLE
Create table of phenotypes

### ISSUE THREAD

**Issue by dlebauer** [genophenoenvo/terraref-datasets#5]
As described in #1 this should be 'wide' format; one row per plot. Where plots have `*_E` and `*_W`, take the mean and remove the trailing subplot designation.

* days to emergence: check season 4 "flag leaf emergence time"
* days to flowering "Flowering Time"
* end of season height = max(canopy_height) for each plot
* Aboveground dry biomass

**Comment by dlebauer** [comment]
Here is some example code for querying data from betydb using python https://terraref.ncsa.illinois.edu/d3m/Scripts/

**Comment by MagicMilly** [comment]
Season 4 data in wide format with one plot per row and column values of `cultivar`, `aboveground_dry_biomass`, `flag_leaf_emergence_time`, and `flowering_time`. Null values filled with empty string.
![image.png](https://images.zenhubusercontent.com/5dae068e86447a00015c37c5/1074bd81-3fac-4182-9eae-d9fb5c4c7462)[https://app.zenhub.com/files/203868729/578d1ba0-0782-4e6b-9229-b1ad30e193cc/download](https://app.zenhub.com/files/203868729/578d1ba0-0782-4e6b-9229-b1ad30e193cc/download)

**Comment by MagicMilly** [comment]
Season 4 trait dataset now includes max canopy height
<img width="812" alt="Screen Shot 2019-10-28 at 09 49 01" src="https://user-images.githubusercontent.com/34486154/67698802-41f4fb80-f968-11e9-889e-28980b0081bf.png">

**Comment by MagicMilly** [comment]
@diatomsRcool @rossarun 
Here is the initial [trait dataset](https://github.com/genophenoenvo/terraref-datasets/blob/gh5-phenotypes/data/four_trait_df.csv) for Season 4 including `sitename`, `cultivar`, `aboveground_dry_biomass`, `flag_leaf_emergence_time`, and `flowering_time` with empty strings for na's. Let me know if you'd like to see additional or different data.

**Comment by MagicMilly** [comment]
@rossarun @diatomsRcool 
Here is the initial [trait dataset](https://github.com/genophenoenvo/terraref-datasets/blob/gh5-phenotypes/data/four_trait_df.csv) for Season 4 including `sitename`, `cultivar`, `canopy_height`, `aboveground_dry_biomass`, `flag_leaf_emergence_time`, and `flowering_time` with empty strings for na's. Let me know if you'd like to see additional / different data.

**Comment by Chris-Schnaufer** [comment]
Waiting for review

**Comment by dlebauer** [comment]
https://github.com/genophenoenvo/terraref-datasets/tree/gh5-phenotypes

**Comment by diatomsRcool** [comment]
Can we add to this, the canonical bits (growing degree days, etc.) the day of max canopy height, day of leaf emergence, day of flowering time. Can we add soil moisture or soil characters to this?

**Comment by diatomsRcool** [comment]
is there a better way to encode the site name so that it is easier to see which plots are on the edge and which in the middle?

**Comment by dlebauer** [comment]
@diatomsRcool yes ... we can create two new columns called 'range' and 'column'

**Comment by Chris-Schnaufer** [comment]
Closing this and opening a new issue

**Comment by MagicMilly** [comment]
Will create new issue for phenotype table with feedback from GenoPhenoEnvo meeting on 11-1-2019
