### ISSUE TITLE
Create list of all cultivars across MAC Seasons 4 and 6 & KSU Data

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#54]
Additionally, identify duplicate cultivars and remove underscores from cultivar names if needed.

**Comment by dlebauer** [comment]
create script that uses function in  https://github.com/PecanProject/bety/issues/185#issuecomment-71534163 to remove duplicates, e.g. functions like:

```sql
update_refs_from_to('cultivars', 
   select id from cultivars where name = 'PI_foobar', 
   select id from cultivars where name = 'PIfoobar')
```

**Comment by MagicMilly** [comment]
Have shared simple cultivar lists in the group's google drive and notified Arun and Ishita on Slack. They are going to review it and most likely ask for more specific queries (i.e. cultivars available in all seasons, all cultivars associated with certain traits).
