### ISSUE TITLE
Continue working on gathering, producing, and organizing material for UA Data Repo

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#58]
Have been working on the required files and directory structure in the google drive, based on this figure from the UA Data Repo: 

<img width="857" alt="Screen Shot 2020-05-07 at 9 13 56 AM" src="https://user-images.githubusercontent.com/34486154/81318782-9679e180-9043-11ea-85df-66339c638eaa.png">

Action items I can work on now to add to google drive for review:
- [ ] scripts / code for pulling data
   - start with https://github.com/terraref/data-publication/blob/master/code/s4s6_sql2csv.R
- [ ] README.md
- [ ] scripts for cleaning / processing data
- [ ] create simple visualizations (i.e. histograms for distributions of certain values) and scripts used to create them
  - build on work that david is doing for data paper
- [x] AUTHORS.md
- [x] LICENSE
- [ ] soil metadata, what the values represent
- [ ] metadata for each data file

**Comment by MagicMilly** [comment]
Will add to and edit Sprint 35's ticket #60 as needed by the end of this Sprint

**Comment by dlebauer** [comment]
please make this an epic and break out 
- metadata curation 
- code
- visualizations
- workflow automation snakemake?

**Comment by MagicMilly** [comment]
Moving this issue to `Done`, linking to Epic #62, and breaking into smaller tasks.
