### ISSUE TITLE
Add to cultivar list comparison across seasons and traits

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#59]
Per feedback from Arun and Ishita, add to the cultivars list which cultivars are available in a combination of seasons (i.e. seasons 4 & 6, all seasons), and add cultivars which are available for pertinent traits.

**Comment by MagicMilly** [comment]
Sent @rossarun and @ishitadebnath this [link](https://github.com/terraref/data-publication/blob/master/metadata/germplasm.csv) with germplasmNames available for MAC Seasons 4 and 6. Would like to add the KSU cultivars to a table like this.

**Comment by MagicMilly** [comment]
Have added the KSU cultivars to a table with all cultivars and seasons, uploaded to [Google Drive](https://drive.google.com/open?id=1JQCEfR3wz7JbqN5TCv6JUt3KCeedUV_b), and notified researchers.

**Comment by rbartelme** [comment]
@MagicMilly it would be good to touch base with @kshefchek to see what cultivars are in the VCF file. Then we'll have all the information that we need for the models. Ultimately, we'll want all cultivars across the three seasons that have genomic data.

**Comment by MagicMilly** [comment]
@rbartelme Thank you for that suggestion! Would be important to have that information in addition to the lists that also have proprietary cultivars mixed in. I'll talk to Kent. 👍

**Comment by MagicMilly** [comment]
Ran into duplicate issues with SQL query results (when adding KSU cultivars) and have individual lists that need to be merged for this ticket to be complete. May need to work with @rbartelme on `R` code since that seems to be the easiest solution compared to Pandas or SQL.

**Comment by MagicMilly** [comment]
Fixed look up table to remove duplicates and include cultivars in season 4, season 6, ksu, and those with genomic data available from the vcf file (thank you @kshefchek). Added to Google [Drive](https://drive.google.com/drive/folders/1ZPcpQV_0Hs3ECVvuyeP-yybAjUWFKIhP?usp=sharing)

<img width="443" alt="Screen Shot 2020-05-22 at 7 56 17 AM" src="https://user-images.githubusercontent.com/34486154/82680877-c6a7af80-9c01-11ea-9376-92b935bf6e0d.png">

Next need to push notebooks / code / SQL script for creating this table
