### ISSUE TITLE
Add data from Breton 2016 to BETYdb etc

### ISSUE THREAD

**Issue by dlebauer** [genophenoenvo/terraref-datasets#61]
* [x] Set up a 1 hr meeting to meet with David so he can walk through how to add data to BETYdb using the UI data entry workflow 
* [ ] ~~record this and put on youtube!!~~! (https://github.com/az-digitalag/organization/issues/230)
* [x] insert data from the attached paper into BETYdb 
* [ ] curate as an additional season / location for PEG analysis

this will add another season and location. [https://app.zenhub.com/files/175507213/9191d26f-e6ff-4d90-8513-5be19051bdc7/download](https://app.zenhub.com/files/175507213/9191d26f-e6ff-4d90-8513-5be19051bdc7/download)

The data we want are in Supplementary file S2 on this page https://www.genetics.org/content/204/1/21.supplemental data  [https://app.zenhub.com/files/203868729/e0005804-aac7-4c5c-85a4-2510f7de86d4/download](https://app.zenhub.com/files/203868729/e0005804-aac7-4c5c-85a4-2510f7de86d4/download)

**Comment by dlebauer** [comment]
will start Friday 10AM

**Comment by dlebauer** [comment]
@MagicMilly I have uploaded these into the terraref version of BETYdb. 

We need to make sure that the README correctly identifies the Breton et al 2016 citation for these data. Let me know if you have any trouble curating these for our collaborators. Or perhaps we should create another issue for that?

**Comment by MagicMilly** [comment]
I've created another issue #67 to finish incorporating weather data with the trait data.

@dlebauer Has the walk-through been uploaded to YouTube?

**Comment by dlebauer** [comment]
https://github.com/az-digitalag/organization/issues/230
