### ISSUE TITLE
Include metadata for all derived data products

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#63]
Can start with metadata generation code from David's data paper

- soil data **priority**
  - link to data and code and relevant gh issue
  - maybe put soil in separate private repository pending discussion w/ Markus (?) 
  - keep this separate and review w/ Markus
- trait data
- environmental data, especially where I used any calculations to add a column (like `gdd` or unit conversions)

**Comment by MagicMilly** [comment]
Soil data with code is currently in a private repo. Please ask if you need access to the [private](https://drive.google.com/file/d/1zXcRzBQqkumPbB_BERTTyTaXZbaoZZNz/view?usp=sharing) Google doc with
- plots as rows
- columns as
    - sand percentages from 0-6" (min, max, mean, std)
    - clay percentages from 0-6" (min, max, mean, std)
    - soil texture values from 0-6" (min, max, mean, std)

**Comment by dlebauer** [comment]
That looks good. If you were to add additional soil layers, I would add a column "max_depth" and "min_depth" for each layer; in the case of this top layer, I would make these 6 and 0. The README should describe what each column contains.

**Comment by MagicMilly** [comment]
README.txt is required for the UA Data Repo. An example for season 4 was uploaded to the Google [drive](https://drive.google.com/file/d/1EjfqEP-8ebHvtY-VrgYrbW3LMHISLtOA/view?usp=sharing), and a screenshot is included of the `Files & Folders` section, but I believe _all_ of the data products may need to be included in a single README for the Data Repo. Machine-readable EML is optional for the Data Repo but will be included as additional material. 
<img width="1001" alt="Screen Shot 2020-06-04 at 10 13 21 AM" src="https://user-images.githubusercontent.com/34486154/83790111-86f2b600-a64c-11ea-86a2-74f755621c96.png">

**Comment by MagicMilly** [comment]
Remaining tasks for this issue have been addressed in new issues #69 and #68
