### ISSUE TITLE
Include scripts for pulling data

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#64]
Can use scripts from David's [data paper](https://github.com/terraref/data-publication/blob/master/code/s4s6_sql2csv.R) and from tutorials [repo](https://github.com/terraref/tutorials)

**Comment by MagicMilly** [comment]
Need to talk to David about this during our 1:1 on 2020-06-08

**Comment by dlebauer** [comment]
the code and data are about to go on dryad ... at this point I think it would be best to start from the [csv files on [google drive](https://drive.google.com/drive/folders/1kgoXR1kJHQWDWcLpkwxfK6e9Qk9zvdUn?usp=sharing). Once it is published we can reference same code and content on Dryad.

**Comment by MagicMilly** [comment]
As discussed, scripts for accessing data (also addressed in Issue #71) will be linked to David's google drive for now until publication.
