### ISSUE TITLE
Add methods and germplasm .csv files to machine-readable metadata

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#68]
In addition to contributors, citations, keywords, etc. - EML metadata that I can finish right now is lacking 

- methods
- germplasm
- variables

which can be found in `.csv` format from David's data paper metadata. I tried using the `set_methods` function with the `EML` package, but may need assistance gettting the proper formatting. Right now the `.eml` document returns something like this for the methods section:
<img width="699" alt="Screen Shot 2020-06-08 at 6 53 38 AM" src="https://user-images.githubusercontent.com/34486154/84039027-81031a80-a955-11ea-999f-f26d03953ca3.png">

**Comment by dlebauer** [comment]
I think first priority should be making sure there is a complete README. Then we can discuss what 
 of this information is necessary to put in the EML.

**Comment by dlebauer** [comment]
these files are now available via Dryad (as well as on Box) in metadata_2.zip https://datadryad.org/stash/dataset/doi:10.5061/dryad.4b8gtht99
