### ISSUE TITLE
Decide how to reference germplasm and methods in README.txt

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#69]
Will ask Chun and Fernando if they would like all metadata in a single `README` for the UA Library Data Repo, or if I can just reference larger `.csv` files like methods, variables, and germplasm.

**Comment by dlebauer** [comment]
1. germplasm: use (reference) germplasm.json files from data-paper. README should state species and refer to the BAP population described in Breton et al 2016
2. methods: lets discuss curating these in protocols.io

**Comment by MagicMilly** [comment]
Chun and Fernando responded that markdown / text files would be more appropriate than `.csv` files, but we will be able to link to these references from the data paper from within the `README.txt` for library repo. 

Currently the README in the for-data-publication [repo](https://github.com/MagicMilly/for-data-publication) (which is being used as a first draft for UA library repo) includes links to these metadata on David's google drive, as addressed in Issue #71 

Discussion and follow up tasks for curating methods on https://www.protocols.io/ included in new ticket #82
