### ISSUE TITLE
Add available wind and humidity data to historical Clemson weather data

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#76]
As a follow up to #67 and at @ishitadebnath's request, add wind data and relative humidity to the interim Clemson weather [data](https://drive.google.com/drive/folders/1x_CtBw7gX4LWmcQxnmi4ck8CB_1_urFg?usp=sharing). May have to look at other weather stations listed on the [NOAA](https://www.ncdc.noaa.gov/data-access) website and can probably find variables needed to calculate relative humidity.

**Comment by dlebauer** [comment]
Unless there is a weather station at the field site with the data we need, we should get these data from a public resource like NARR or daymet ... 

start by providing VP & Temp from daymet. https://github.com/bluegreen-labs/daymetpy we can later figure out how to convert VP to RH 

Alternatively, this has RH https://clim-engine.appspot.com/climateEngine

**Comment by MagicMilly** [comment]
Updated interim Clemson weather data can be found on the Google [drive](https://drive.google.com/drive/folders/1tQat5wA3xuBsgsE67n4lJIj1rhoZHNKA?usp=sharing) replaced the previous version. The updated data is more precise using the coordinates of the Clemson University Pee Dee Research and Education Center. 

The notebook used to transform the raw weather data can be found [here](https://github.com/MagicMilly/for-data-publication/tree/main/notebooks).

Updated weather data will be integrated with the trait data, which will also produce an updated growing degree days to flowering data product.

**Comment by MagicMilly** [comment]
##### Raw Clemson weather data is now available on Cyverse (links will start an automatic download)
- daily max and min temperatures in Celsius and precipitation in mm for [2014](https://de.cyverse.org/dl/d/1114BCCC-FC8A-4E37-B4FD-991B57902B50/clemson_raw_daily_2014_updated.csv)
- daily max and min [relative humidity](https://de.cyverse.org/dl/d/1828EE4A-1B6B-4127-B1BF-6BDF3D9D42E9/clemson_rh_2014.csv)
- daily [wind speed](https://de.cyverse.org/dl/d/D114C087-F204-47A1-98E8-1D8ECEABF297/climate_engine_wind_speed_2014.csv) (assumed to be an average value, still looking for official documentation to confirm this)

##### Raw weather data also on Google [drive](https://drive.google.com/drive/folders/1Oaoz7vy5CjcCWFwCED7XZA1K0rmIflcz?usp=sharing)

##### Updated clemson_days_to_flowering (GDD changed with new temperatures) is now on Google [drive](https://drive.google.com/drive/folders/1l_ZQCbbVzpSie-OSthtkfhytbZzxSEJo?usp=sharing) and [GitHub](https://github.com/MagicMilly/for-data-publication/tree/main/data/processed) 

##### Updated cleaning notebook using updated weather data for days to flowering on [GitHub](https://github.com/MagicMilly/for-data-publication/tree/main/notebooks)
