### ISSUE TITLE
Follow-up Action Items to Exploring NEON data

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#78]
Outcome: after exploring available data using the Shiny app as addressed in issue #74, learn to navigate and find needed data from NEON / NPN directly. 

Tasks / Focus
- [x] conversation with Ryan and / or Tyson about curating microbe + plants + soil + weather data
- [x] focus on sites with data described in issue #74 
- [ ] focus on black poplar / willow / cottonwood - black poplar mentioned in proposal, and we also have the genotype

**Comment by MagicMilly** [comment]
Moving to next Sprint due to no specific follow-up actions being identified yet. Questions and clarification from #74 in previous Sprint will direct the tasks needed to complete this ticket.

**Comment by rbartelme** [comment]
@MagicMilly I should have some lat/long coordinates, sites, and dates for all the soil metagenomes by the end of the day today, or tomorrow.

**Comment by MagicMilly** [comment]
Bumping to next Sprint, need to discuss how to move forward with David and Ryan

**Comment by MagicMilly** [comment]
~Bumping to next Sprint~ Removing milestone due to issues with the NEON data which are still being resolved

**Comment by dlebauer** [comment]
what are the current blockers on this?

**Comment by MagicMilly** [comment]
@rbartelme will have the answer to this but also said that my current follow-up action item #95 is not blocked.

**Comment by rbartelme** [comment]
@MagicMilly Yep! Feel free to roam the data in #95

**Comment by MagicMilly** [comment]
Removing point estimate and closing this issue due to having more specific tasks defined in other tickets like #95 and #96
