### ISSUE TITLE
Add drought treatment and blocking information to Season 4 

### ISSUE THREAD

**Issue by dlebauer** [genophenoenvo/terraref-datasets#85]
I just remembered that there was an unplanned drought treatment in Season 4. This information is in the database and the summarized csv files prepared for the Dryad deposition. I am not sure if this has been included in the Season 4 and 6 datasets, but it is important for the analysis of Season 4 data.

There is a temporal dynamic that should be included. Specifically, the experiment was irrigated except that irrigation was turned off for two weeks. Half of the field had no irrigation Aug 1-14 and half of the plots had no irrigation Aug 15-30

As indicated in the experimental design for season 4 

- experiment description: https://terraref.ncsa.illinois.edu/bety/api/v1/experiments?name=~MAC+Season+4:+All+BAP+With+Late+Season+Drought) 

> A late season drought experiment along drip lines was established as part of the field campaigns in the latter part of season 4. This was not a pre-planned drought study, and only temporary water limited zones for the field campaign. There were two treatments. Irrigation was turned off during the first two weeks of August in the first treatment and irrigation was turned off during the second two weeks of August in the second treatment. Additional discussion can be found in https://github.com/terraref/reference-data/issues/196.
> Ranges blocked by height of BAP accessions: \r\n* Short: Ranges 11, 20, 46, 50.\r\n* Medium: Ranges 10, 12, 18, 24, 27, 29, 31, 33, 38, 51; \r\n* Tall: Ranges 3-9, 13-17,19, 21-23, 25, 26, 28, 30, 32, 35-37, 39-45, 47-49, 52\r\n\r\nDrought Treatments:\r\n* no irrigation Aug 1-14 in Cols 5, 6, 7, 8, 12, 13, 14, 15 and 16\r\n* no irrigation Aug 15-30 in Cols 1, 2, 3, 4, 9, 10, and 11\r\n"

- treatment descriptions: https://terraref.ncsa.illinois.edu/bety/api/v1/treatments?name=~Season+4

@MagicMilly if you are using the data being prepared for dryad, I will update these and let you know.

1. [x] please update data to include the 'treatment' column? This should be straightforward - I think previously this column was filtered out, but it should appear in the query results.
2. [x] add an additional column to season 4 data that identifies the experimental blocking by height

**Comment by rbartelme** [comment]
@MagicMilly I think @dlebauer is saying that every cultivar with the drought stressed treatment starting on August 1 should be filtered by date (Start of season through July 31st) and then the other treatment started on August 15th, so those cultivars should be date filtered (Start of season through August 14th).

**Comment by rbartelme** [comment]
@MagicMilly This is a big blocker for me at the moment.

**Comment by dlebauer** [comment]
@MagicMilly actually, I am not as certain that they should be filtered on date - that might be something to leave up to the people doing statistical analysis. In the case that we want to ignore the treatments, users can filter the Season 4 data by date (>Aug 1). But if someone wants to investigate tolerance to drought stress, they might either add a categorical factor "Treatment". For time series analysis, a column named 'irrigation' that is TRUE when the irrigation is on, FALSE when off could be useful.

Irrigation TRUE v FALSE could be treated like weather - this boolean is simpler and just as effective as calculating the actual amount of water applied. i.e. we do have irrigation_rate but irrigation was always sufficient to relieve water stress. See https://github.com/terraref/reference-data/issues/196 for hints on querying and calculating irrigation_rate ...

**Comment by MagicMilly** [comment]
The drought treatments were added to the Season 4 weather data as addressed in Issue #87, but the blocking information, column alignment, filling NAs, and updated cleaning notebook will be moved to next Sprint.

**Comment by rbartelme** [comment]
@MagicMilly does the drought treatment map properly to the field if it's not in the cultivar trait data? I thought the weather data were from a station away from the field, and that the drought treatment was specific to where a given cultivar was planted.

**Comment by MagicMilly** [comment]
@dlebauer Range 34 is missing from the [experiment description](https://terraref.ncsa.illinois.edu/bety/api/v1/experiments?name=~MAC+Season+4:+All+BAP+With+Late+Season+Drought) you shared, but this [spreadsheet](https://drive.google.com/file/d/0B1OR5-zeXagnd2dKQUN5YjRfTlU/view?usp=sharing) indicates that Range 34 was blocked by a tall height, so I will use that information for the new `blocking_height` column.

**Comment by MagicMilly** [comment]
- Have added drought and blocking treatments for selected traits to [GitHub](https://github.com/MagicMilly/for-data-publication/tree/main/data/processed) and Google [Drive](https://drive.google.com/drive/folders/1gbB3Aa1F8ckyFk7qPr3LEiZCKPxk8DqJ?usp=sharing). 
- New season 4 cleaning notebook and separate season 4 weather data cleaning notebooks can be found on [GitHub](https://github.com/MagicMilly/for-data-publication/tree/main/notebooks).


Updated README included in follow up ticket #91
