### ISSUE TITLE
Prepare spreadsheet for Jaiswal group to annotate TERRA REF data with TO terms

### ISSUE THREAD

**Issue by dlebauer** [genophenoenvo/terraref-datasets#9]
From kickoff notes: 
> THIS IS CRITICAL to the ability to cross reference the data and use them in an integrated way that informs. Important considerations need to be made for also contributing new terms to TO, given the complexity and wealth of data from TERRA REF.

@diatomsRcool and Pankaj where to start? How can we help?

**Comment by dlebauer** [comment]
@MagicMilly please create a table with all of the combinations of variables.name and methods.name in the TERRA REF dataset that you are preparing; then we can discuss with Pankaj et al about how to fill it out.

**Comment by MagicMilly** [comment]
@dlebauer @diatomsRcool Here is the work-in-progress [spreadsheet](https://docs.google.com/spreadsheets/d/1o13Gy0p6-1ncgWwZ_QNM4yJxugf533o3DL-7zk4sn9g/edit?usp=sharing). Anybody should be able to comment - please let me know if you have trouble accessing or commenting.

**Comment by MagicMilly** [comment]
First draft of [TO table](https://docs.google.com/spreadsheets/d/1o13Gy0p6-1ncgWwZ_QNM4yJxugf533o3DL-7zk4sn9g/edit?usp=sharing). Still need to fill in some missing values once I find more information. Four traits have ontology identifiers in the dataset, which I included in the table:
* `lodging_present`
* `stem_elongated_internodes_number`
* `emergence_count`
* `plant_basal_tiller_number`

**Comment by MagicMilly** [comment]
Example code used to find data for spreadsheet:

```
unique_traits = df.trait.unique()
for trait in unique_traits:
    
    print(f'All unique units for {trait}: {df.loc[df.trait == trait].units.unique()}')
```
All code used can be found in this [notebook](https://github.com/genophenoenvo/terraref-datasets/blob/gh5-phenotypes/notebooks/ontology_annotations.ipynb)

**Comment by MagicMilly** [comment]
[TO table](https://docs.google.com/spreadsheets/d/1o13Gy0p6-1ncgWwZ_QNM4yJxugf533o3DL-7zk4sn9g/edit?usp=sharing) ready for review ahead of meeting on Friday. Will share link in group's Slack channel. 

Missing values include
* units for photosynthesis-related parameters
* units for leaf greenness measurements
* units and descriptions for some leaf angle measurements taken with 3D scanner

**Comment by diatomsRcool** [comment]
I sent the link to Laurel Cooper on Pankaj's team.

**Comment by dlebauer** [comment]
* what uris should we use?
* how do we interpret / label the comments about exact, subclass, related, and other ontology terms?

Next step: convert this to a json dictionary

**Comment by dlebauer** [comment]
looks great ... next step is to create a lookup table https://github.com/genophenoenvo/terraref-datasets/issues/21
