### ISSUE TITLE
Refactor code for cleaning soil data

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#90]
Currently code is repetitive for each of seven soil bands. Needs refactoring with functions before PR for better understanding of the code.

**Comment by MagicMilly** [comment]
Have not started this yet so am bumping to next Sprint

**Comment by dlebauer** [comment]
could you please link to existing code?

**Comment by MagicMilly** [comment]
Here is the [notebook](https://github.com/genophenoenvo/soil-data/blob/magic-milly-gh70/notebooks/soil_data_cleaning.ipynb) - it was on its own branch. This is an example of the code I used for _every_ band for sand and clay:
<img width="1101" alt="Screen Shot 2020-08-04 at 8 17 59 AM" src="https://user-images.githubusercontent.com/34486154/89311622-17d51600-d62b-11ea-97c9-4d5f775f0630.png">

**Comment by MagicMilly** [comment]
[Pull Request](https://github.com/genophenoenvo/soil-data/pull/1) for soil-data repo
