### ISSUE TITLE
Add ontologies, methods, and traits json files after PR is approved to BrAPI

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#92]
As a followup to issue #77 and #36, after ontologies.json, methods.json, and traits.json are approved, finish these steps:

- [ ] review api/observationunits.py and figure out how to read in ontologies.json and ammend the results with these terms.

- Ask David if / when you get stuck
- Work with @KristinaRiemer if needed / she's available

**Comment by MagicMilly** [comment]
Still need to add `methods.json` and `traits.json` as Pull Requests, carryover from previous Sprint

Additionally, `ontologies.json` is not valid json, so will be updating that file as well.

**Comment by MagicMilly** [comment]
Created this [repo](https://github.com/MagicMilly/brapi-contributions) for code used to generate these files. Worked on functions during mentorship session with @julianp

**Comment by julianpistorius** [comment]
@dlebauer After reviewing our notes from the meeting, we're not sure where the Ontology Annotations should be 'slotted/grafted' in to the ObservationUnit results.

See <https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI-Phenotyping/2.0#/ObservationUnit>

1. Do we need to return the ontology annotations as a JSON dict in the `additionalInfo` field? 
2. Or do we link it in some other way?

Thanks!

**Comment by dlebauer** [comment]
Sorry about that - I must have been looking at the wrong spot in the documentation. Also, we are following the 1.3 spec (https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI/1.3). 

The key requirement here is to annotate the data with ontology terms, and the secondary requirement is to do so following the BrAPI spec. 

I think this will show up in the GET methods for /method, /variables, and /study/[studyDbId}/observationvariables

**Comment by MagicMilly** [comment]
The csv we discussed which includes annotations associated with 
- observationVariableName
- traitDescription
- scaleName
- methodName
- ontologyDbId
- URL (this value is usually nested in another dictionary like ontologyReference)
- traitName

was added to the [PR](https://github.com/terraref/brapi/pull/44/commits/9e1fa8dd268e8db25011374e568e7f9d4c01a07d#)
