### ISSUE TITLE
Transfer data and notebooks from personal repo to GenoPhenoEnvo / CyVerse

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#93]
As a follow-up to ticket #91, need to add updated 

- notebooks
- data
- README

to this terra-ref datasets repo as a PR. Tyson and / or Ryan can help with getting these onto CyVerse, especially for pulling data rather than using `.csv` files as input.

**Comment by MagicMilly** [comment]
Bumping to next Sprint. Need to talk to clarify things with Tyson and Ryan re: what should be on CyVerse from my end, or if they only want me to add notebooks to the repo that they will then move themselves.

**Comment by rbartelme** [comment]
@MagicMilly I think @tyson-swetnam will have some input related to this. He's busy with FOSS today, but I think he has a good idea of where these need to go, as well as adding some info in the readthedocs among other things.

**Comment by MagicMilly** [comment]
Thanks for letting me know. This would be helpful since I haven't been keeping track of the process very well.

**Comment by MagicMilly** [comment]
As a follow-up from UA NSF HDR meeting, start with uploading notebooks to CyVerse, reading ReadTheDocs, and chat with Tyson

**Comment by MagicMilly** [comment]
This has been done with raw and processed data, the Dryad data, and with notebooks (in the `genophenoenvo` and `terraref` directories on CyVerse). It is still a work-in-progress, though, to keep uploading to CyVerse as code gets updated or different formats of data are generated.
