### ISSUE TITLE
Search NPN for Days and GDD to Flowering

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#96]
- See if NPN data products already include GDD to flowering, or if this needs to be calculated. 
- Follow up with NPN / Kathy Gerst to see what code she has used and if there is already a model being used to predict date of flowering.

**Comment by dlebauer** [comment]
start to prepare dataset that has ggd to flowering for Populus nigra, including `lat, lon, year, gdd to flowering`

**Comment by MagicMilly** [comment]
Bumping to next Sprint because the dataset has not been started yet, though I have familiarized myself with accessing NPN data

**Comment by MagicMilly** [comment]
E-mailed Kathy Gerst today to ask about a predictive model for days to flowering for Populus nigra. Follow-up action items will be discussed with David and described in Issue #105
