### ISSUE TITLE
Upload Dryad data with citation to CyVerse

### ISSUE THREAD

**Issue by MagicMilly** [genophenoenvo/terraref-datasets#98]
Will talk to Tyson if I run into permission issues.

**Comment by MagicMilly** [comment]
@dlebauer I added all of the Dryad content to CyVerse in the terraref/public folder. I applied the same metadata to every file and folder within `public`, but I can change that to be more specific or remove where it's not needed.

**Comment by MagicMilly** [comment]
Metadata contained the wrong doi, so I need to redo the bulk metadata upload for this ticket to be complete.

**Comment by MagicMilly** [comment]
These data should now be viewable in the [Data Commons](https://datacommons.cyverse.org/browse/iplant/home/shared/terraref/public). I was able to apply the bulk metadata template to the high-level folders, which also shows when you select those files while browsing in the DC (like a landing page).
![Screen Shot 2020-09-14 at 1.53.02 PM.png](https://images.zenhubusercontent.com/5dae068e86447a00015c37c5/3cd1edb7-ac5c-4385-851d-d7e24c3aeb3e)
My understanding is that the `public` folder will be used for more open data in addition to the Dryad publication, so I did not apply any metadata that would look like a landing page.
![Screen Shot 2020-09-14 at 1.55.10 PM.png](https://images.zenhubusercontent.com/5dae068e86447a00015c37c5/16186d27-edd4-455b-955a-8e0b4c461317)

**Comment by dlebauer** [comment]
thanks for doing this - the public folder should be used to mimic the contents of the Dryad submission and should thus have a landing page. Other public but unpublished data can go under the terraref/ folder. 

The terraref/genomics folder is also 'public'. It should go under 'public' but we can't change the urls at this point. But could you move the landing page that is currently at https://datacommons.cyverse.org/browse/iplant/home/shared/terraref to the terraref/genomics folder? It should also have rights == CC0 and a the dryad citation. Maybe open a new issue if necessary.

**Comment by MagicMilly** [comment]
Closing this issue; follow-up ticket #102 for David's feedback
